schema_version: "1.0"
mcp_name: "Greek Law MCP"
jurisdiction: "GR"

sources:
  - name: "Εθνικό Τυπογραφείο (search.et.gr + et.gr FEK archive)"
    authority: "Εθνικό Τυπογραφείο (National Printing Office of Greece)"
    official_portal: "https://search.et.gr/el/search-legislation/"
    retrieval_method: "API"
    update_frequency: "unknown"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "government_terms"
      url: "https://et.gr/oroi-chrisis/"
      summary: "Official FEK texts are published by the National Printing Office; use is subject to official site terms."
    coverage:
      scope: "Official metadata for selected Greek laws via search API, with canonical FEK PDF URLs from official storage"
      limitations: "No official structured article-level API endpoint was found; full legal text is available as PDF only"
    languages:
      - "el"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-21"
